name: Docker_build
#
on:
  push:
    tags: # tag更新时触发此workflow
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@master
      with:
        images: chironsssss/honeycomb

    - uses: actions/checkout@master
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: chironsssss/honeycomb
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tag_names: true